"""
Register all financial tools for LangGraph.
"""

from langchain_core.tools import BaseTool

from app.tools import (
    analyze_budget,
    fifty_thirty_twenty_rule,
    savings_goal,
    time_to_goal,
    sip_maturity,
    required_sip,
    calculate_emi,
    loan_affordability,
    analyze_expenses,
    detect_overspending,
    analyze_portfolio,
    rebalance_portfolio,
    portfolio_summary,
    analyze_stock,
    compare_stocks,
    stock_price,
    search_stock,
    suggest_stocks,
    evaluate_mutual_fund,
    lump_sum_projection,
    income_tax_old_regime,
    income_tax_new_regime,
    compare_tax_regimes,
    convert_currency,
    percentage,
    compound_interest,
    simple_interest,
    future_value,
    profit_loss,
)

FINANCIAL_TOOLS: list[BaseTool] = [
    analyze_budget,
    fifty_thirty_twenty_rule,
    savings_goal,
    time_to_goal,
    sip_maturity,
    required_sip,
    calculate_emi,
    loan_affordability,
    analyze_expenses,
    detect_overspending,
    analyze_portfolio,
    rebalance_portfolio,
    portfolio_summary,
    analyze_stock,
    compare_stocks,
    stock_price,
    search_stock,
    suggest_stocks,
    evaluate_mutual_fund,
    lump_sum_projection,
    income_tax_old_regime,
    income_tax_new_regime,
    compare_tax_regimes,
    convert_currency,
    percentage,
    compound_interest,
    simple_interest,
    future_value,
    profit_loss,
]